export const STAGE_BUCKET = 'cdk-lambda-deployer-stage'
export const PROD_BUCKET = 'cdk-lambda-deployer-prod'
export const METADATA_FILE_NAME = 'metadata.json'
export const FUNCTIONS_CHANGES_SUMMARY_FILE_NAME = 'functions/changes_summary.json'
export const LOCK_FILE = 'updating_functions.lock'
