export const STAGE_BUCKET = 'minisuper-api-functions-stage'
export const PROD_BUCKET = 'minisuper-api-functions'
export const LOCK_FILE = 'updating_libs.lock'
export const LIBS_METADATA_FILE_NAME = 'libs/metadata.json'
export const LIBS_CHANGES_SUMMARY_FILE_NAME = 'libs/changes_summary.json'
