export const STAGE_BUCKET = 'cdk-lambda-deployer-stage'
export const PROD_BUCKET = 'cdk-lambda-deployer-prod'
export const LOCK_FILE = 'updating_libs.lock'
export const LIBS_METADATA_FILE_NAME = 'libs/metadata.json'
export const LIBS_CHANGES_SUMMARY_FILE_NAME = 'libs/changes_summary.json'
